// <auto-generated />
namespace MVCMusicStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addalbummodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addalbummodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201703031728359_add-album-model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
